= Connection reference for Snowflake
:last_updated: 12/10/2020
:linkattrs:
:experimental:
:page-layout: default-cloud
:description: Learn about the fields used to create a Snowflake connection.
:page-aliases: /admin/ts-cloud/ts-cloud-embrace-snowflake-connection-reference.adoc, /data-integrate/embrace/embrace-snowflake-reference.adoc

Here is a list of the fields of a Snowflake connection.
You need specific information to establish a seamless and secure connection.
All fields are required, except where noted.
[#connection-name]
Connection name::  Enter a new Snowflake connection name.
[#connection-description]
Connection description::
Provide a short description of the connection.
_(Optional)_
[#account-name]
Account name::
Enter the account name associated with your Snowflake connection.
The account name is part of the URL that you use to access the Snowflake UI.
- If you are using the Snowflake classic UI, it is the portion of the URL before `snowflakecomputing.com`.
+
`<account name>.snowflakecomputing.com`
+
*Example*: If your URL is `+https://abcd.xyz.efg.snowflakecomputing.com+`, your account name is `abcd.xyz.efg`.
- If you are using the Snowsight UI, it is the portion after the region.
+
`app.snowflake.com/<region>/<account name>`
+
*Example* (using the US East Ohio region): https://app.snowflake.com/us-east-2.aws/abcd.xyz.efg.us-east-2.aws

Assume that the *account name* is _abcd.xyz.efg_.

[width="100%",cols="20%,40%,40%" options="header"]
|====================
|
Cloud platform  | Region | Full account name
| *AWS* | US East (N. Virginia) | abcd.xyz.efg.us-east-1
|  | US East (Ohio) | abcd.xyz.efg.us-east-2.aws
|  | US West (Oregon) | abcd.xyz.efg
|  | Canada (Central) | abcd.xyz.efg.ca-central-1.aws
|  | EU (Ireland) | abcd.xyz.efg.eu-west-1
|  | EU (Frankfurt) | abcd.xyz.efg.eu-central-1
|  | Asia Pacific (Singapore) | abcd.xyz.efg.ap-southeast-1
|  | Asia Pacific (Sydney) | abcd.xyz.efg.ap-sowtheast-2
| *GCP* *_- Preview_* | us-central1 (Iowa) | abcd.xyz.efg.us-central1.gcp
| *Azure* | East US 2 | abcd.xyz.efg.east-us-2.azure
|  | US Gov Virginia | abcd.xyz.efg.us-gov-virginia.azure
|  | Canada Central | abcd.xyz.efg.canada-central.azure
|  | West Europe | abcd.xyz.efg.west-europe.azure
|  | Australia East | 	abcd.xyz.efg.australia-east.azure
|====================

[#user]
User::  Enter the Snowflake account username.
[#password]
Password::  Enter the Snowflake account password.
[#role]
Role::  Specify the privilege of the user.
[#warehouse]
Warehouse::  Specify the warehouse associated with the connection.
[#database]
Database::
Specify the database associated with the account.
_(Optional)_
[#schema]
Schema::  Specify the schema associated with the database.
[#oauth]
OAuth:: Enter the OAuth client ID associated with the Snowflake database.
[#oauth-client-secret]
OAuth client secret:: Enter the OAuth client secret associated with the Snowflake database.
