= ThoughtSpot {product} Documentation
:page-layout: home-branch-blank

++++
<style>
.home h2, .home h3, .home h4, .home h5, .home h6, .doc h1, .doc h2, .doc h3, .doc h4, .doc h5, .doc h6 {
    color: #444;
    font-weight: 500;
    font-family: Optimo-Plain,sans-serif;
    -webkit-hyphens: none;
    -ms-hyphens: none;
    hyphens: none;
    line-height: 1.3;
    margin: 1rem 0 0;
}

h2#_whats_new_in_thoughtspot_cloud {
    font-weight: 450;
    font-size: larger;
}

h3#_previous_releases_cloud {
    font-weight: 300;
    font-size: medium;
}

.dlist dt {
    font-style: normal !important;
}

b, dt, strong, th {
    font-weight: 500;
    font-size: .84444rem;
    line-height: 1.6;
}

.home .box-wide p {
    margin: medium;
    color: #444;
    font-size: .84444rem;
    line-height: 1.6;
}

.box-wide-columns {
    width: 82%;
    margin: 0 auto;
    padding-right: 25px;
}

td {
    font-size: 13px;
    padding: 10px;
}

.modal-inner {
    top: 20px !important;
    border-radius: 8px !important;
    max-width: 90% !important;
    max-height: 85% !important;
}

.mode-image {
    width: 80px !important;
    margin-top: -15px !important;
    margin-bottom: 1px !important;
}
</style>
++++

++++
<div class="box-button-columns">
    <div class="box-button"><a href="https://docs.thoughtspot.com/cloud/latest" class="panel-2">
      <span>
    <h2>
      Get Started
    </h2>
    </span>
    </a></div>
    <div class="box-button"><a href = "https://docs.thoughtspot.com/software/latest" class = "panel-2">
    <h2>
      Navigate and organize content
    </h2>
    </a></div>
  <div class="box-button"><a href="https://developers.thoughtspot.com/docs/" class="panel-2">
      <span>
    <h2>
      Connect your database
    </h2>
   </span>
    </a></div>
  Query and analyze data
      <span>
    </span>
    </a></div>
 </div>


++++

