= ThoughtSpot {form-factor} Documentation
:page-layout: home-branch-blank

++++
<style>
.home h2, .home h3, .home h4, .home h5, .home h6, .doc h1, .doc h2, .doc h3, .doc h4, .doc h5, .doc h6 {
    color: #444;
    font-weight: 500;
    font-family: Optimo-Plain,sans-serif;
    -webkit-hyphens: none;
    -ms-hyphens: none;
    hyphens: none;
    line-height: 1.3;
    margin: 1rem 0 0;
}

h2#_whats_new_in_thoughtspot_cloud {
    font-weight: 450;
    font-size: larger;
}

h3#_previous_releases_cloud {
    font-weight: 300;
    font-size: medium;
}

.dlist dt {
    font-style: normal !important;
}

b, dt, strong, th {
    font-weight: 500;
    font-size: .84444rem;
    line-height: 1.6;
}

.home .box-wide p {
    margin: medium;
    color: #444;
    font-size: .84444rem;
    line-height: 1.6;
}

.box-wide-columns {
    width: 82%;
    margin: 0 auto;
    padding-right: 25px;
}

td {
    font-size: 13px;
    padding: 10px;
}

.modal-inner {
    top: 20px !important;
    border-radius: 8px !important;
    max-width: 90% !important;
    max-height: 85% !important;
}

.mode-image {
    width: 80px !important;
    margin-top: -15px !important;
    margin-bottom: 1px !important;
}

@media only screen and (min-width: 1216px) {
    .box-button-columns {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-wrap: wrap;
        flex-wrap: wrap;
        /* margin: 0 auto; */
        margin-left: -18px !important;
        width: 100% !important;
    }
}

@media only screen and (min-width: 1024px) {
    .box-button-columns {
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-wrap: wrap;
        flex-wrap: wrap;
        width: 100% !important;
    }
}
</style>
++++

{form-factor} is a simple, self-service, chat-based interface for asking questions and getting answers in natural language from your data stored in a cloud data warehouse. {form-factor} enables you to talk to your data in a whole new way.

xref:{latest}@cloud:notes.adoc[without root]
xref:{latest}@cloud:ROOT:notes.adoc[with root]

xref:notes.adoc[]



